.gitignore
build.gradle
src/main/java/bokjak/bokjakserver/common/dummy/CategoryDummy.java
src/main/java/bokjak/bokjakserver/config/security/SecurityConfig.java
src/main/java/bokjak/bokjakserver/domain/category/controller/CategoryController.java
src/main/java/bokjak/bokjakserver/domain/category/dto/CategoryDto.java
src/main/java/bokjak/bokjakserver/domain/category/dto/CheckBoxFilter.java
src/main/java/bokjak/bokjakserver/domain/category/repository/LocationCategoryRepository.java
src/main/java/bokjak/bokjakserver/domain/category/repository/SpotCategoryRepository.java
src/main/java/bokjak/bokjakserver/domain/category/service/CategoryService.java
src/main/java/bokjak/bokjakserver/domain/congestion/model/CongestionLevel.java
src/main/java/bokjak/bokjakserver/domain/congestion/model/WeeklyCongestionStatistic.java
src/main/java/bokjak/bokjakserver/domain/spot/model/Spot.java

빌드, category
- category 전체조회 API
- build 정상적으로 되도록 .gradle 수정
- 엔티티 수정
@woo0doo 일단 KakaoService 에러 나는 부분은 주석처리해뒀음
이제 빌드 과정 체크하고 push 하는게 좋을듯. 이거 테스트에서 assert 에러 은근 많이 나네ㅎ.

 [WBS1-53] Category API

---

src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
src/main/java/bokjak/bokjakserver/common/dummy/CategoryDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/DummyLocationCategory.java
src/main/java/bokjak/bokjakserver/common/dummy/DummySpotCategory.java
src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
src/main/java/bokjak/bokjakserver/domain/category/dto/CategoryDto.java
src/main/java/bokjak/bokjakserver/domain/category/dto/CongestionHistoricalDateChoice.java
src/main/java/bokjak/bokjakserver/domain/category/dto/CongestionLevelChoice.java
src/main/java/bokjak/bokjakserver/domain/category/dto/EnumDayValue.java
src/main/java/bokjak/bokjakserver/domain/category/dto/EnumModel.java
src/main/java/bokjak/bokjakserver/domain/category/dto/EnumValue.java
src/main/java/bokjak/bokjakserver/domain/category/exception/CategoryException.java
src/main/java/bokjak/bokjakserver/domain/category/service/CategoryService.java
src/main/java/bokjak/bokjakserver/domain/user/service/KakaoService.java
src/test/java/bokjak/bokjakserver/BokjakserverApplicationTests.java

- 예외처리
- 리팩토링 
- 체크박스 부분 Map -> enum 변경 
- 변수명 리팩토링
- 예외처리
- 빌드 문제 해결

[WBS1-53] Category

---

.gitignore
build.gradle
gradlew
src/main/java/bokjak/bokjakserver/common/constant/MessageConstants.java
src/main/java/bokjak/bokjakserver/common/dummy/DummyLocationCategory.java
src/main/java/bokjak/bokjakserver/common/exception/GlobalExceptionHandler.java
src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
src/main/java/bokjak/bokjakserver/config/security/SecurityConfig.java
src/main/java/bokjak/bokjakserver/util/s3/AwsS3Config.java
src/main/java/bokjak/bokjakserver/util/s3/S3SaveDir.java
src/main/java/bokjak/bokjakserver/util/s3/controller/AwsS3Controller.java
src/main/java/bokjak/bokjakserver/util/s3/dto/AwsS3Dto.java
src/main/java/bokjak/bokjakserver/util/s3/exception/AwsS3Exception.java
src/main/java/bokjak/bokjakserver/util/s3/service/AwsS3Service.java

- S3 전반적인 구현
- ExceptionHandler 추가
- StatusCode 추가
- 구현 : S3 업로드, 수정, 삭제
- 수정 :  SecurityConfig에서 S3 파일 업로드 엔드포인트 URL 추가
- application.yml 수정됐음.
@woo0doo 못 잡은 예외 처리가 다 access denied (security쪽인듯)로 처리되고 있어서 별도의 핸들러를 만들었음.
이제 우리 실수로 나는 에러 혹은 분기처리 못한 에러들은 다 이걸 타고 가게 됨. 
어생?

[WBS1-79] Aws s3

---

gradlew
src/main/java/bokjak/bokjakserver/common/exception/GlobalExceptionHandler.java
src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
src/main/java/bokjak/bokjakserver/util/s3/S3SaveDir.java
src/main/java/bokjak/bokjakserver/util/s3/controller/AwsS3Controller.java
src/main/java/bokjak/bokjakserver/util/s3/dto/AwsS3Dto.java
src/main/java/bokjak/bokjakserver/util/s3/service/AwsS3Service.java

큰 변경사항은 없음.
- GlobalExceptionHandler에 클라이언트 에러 파트 추가
- AWS S3 요청 유효성 검사 추가
앞으로 Controller에 유효성 검사(@Valid)까지 포함합시다 (리팩토링때 해도 괜찮을듯)

[WBS1-79] Aws S3 유효성 검사 파트 리팩토링

---

src/main/java/bokjak/bokjakserver/common/dummy/UserDummy.java
src/main/java/bokjak/bokjakserver/domain/report/exception/ReportException.java
src/main/java/bokjak/bokjakserver/domain/user/controller/AuthController.java
src/main/java/bokjak/bokjakserver/domain/user/dto/AuthDto.java
src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java

Feat/User dummy 추가 , Refactor/닉네임 검증

---

src/main/java/bokjak/bokjakserver/domain/notification/model/Notification.java
src/main/java/bokjak/bokjakserver/domain/notification/model/NotificationType.java
src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
src/main/java/bokjak/bokjakserver/domain/user/dto/UserDto.java
src/main/java/bokjak/bokjakserver/domain/user/model/User.java
src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java

유저 프로필 업데이트 추가
현재 구현하고 있는 notification도 user domain에 수정되어 함께 커밋합니다.

feat: 유저 프로필 업데이트 추가

---

src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
src/main/java/bokjak/bokjakserver/domain/report/controller/ReportController.java
src/main/java/bokjak/bokjakserver/domain/report/dto/ReportDto.java
src/main/java/bokjak/bokjakserver/domain/report/model/Report.java
src/main/java/bokjak/bokjakserver/domain/report/repository/ReportRepository.java
src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepository.java
src/main/java/bokjak/bokjakserver/domain/user/model/User.java

신고 생성 기능 추가
spot, comment repository 생성

[WBS1-123] feat: 신고 생성

---

src/main/java/bokjak/bokjakserver/common/dummy/CategoryDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/CommentDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/CongestionDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/LocationDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/SpotDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/UserDummy.java
src/main/java/bokjak/bokjakserver/domain/bookmark/model/LocationBookmark.java
src/main/java/bokjak/bokjakserver/domain/bookmark/model/SpotBookmark.java
src/main/java/bokjak/bokjakserver/domain/category/model/LocationCategory.java
src/main/java/bokjak/bokjakserver/domain/category/model/SpotCategory.java
src/main/java/bokjak/bokjakserver/domain/comment/model/Comment.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
src/main/java/bokjak/bokjakserver/domain/congestion/model/Congestion.java
src/main/java/bokjak/bokjakserver/domain/congestion/model/DailyCongestionStatistic.java
src/main/java/bokjak/bokjakserver/domain/congestion/model/WeeklyCongestionStatistic.java
src/main/java/bokjak/bokjakserver/domain/location/model/Location.java
src/main/java/bokjak/bokjakserver/domain/spot/model/Spot.java
src/main/java/bokjak/bokjakserver/domain/spot/model/SpotImage.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotImageRepository.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepository.java
src/main/java/bokjak/bokjakserver/domain/user/dto/AuthDto.java
src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java

신고쪽 개발에 필요해서 더미 데이터 따로 PR 올려요
구현 : Spot, Comment 더미 데이터
수정 : 엔티티 not null 속성 추가

Spot, Comment 더미 데이터

---

Dockerfile
build.gradle

github actions, docker 배포 파이프라인용 변수 설정
CI CD는 처음이라 시행착오 꽤 있을 예정... 관련 PR 올라올라오면 그러려니 해주세요. 
앞으로 application.yml 파일 수정되면 
파일 내용 통째로 base64로 변환 -> [settings](https://github.com/Akatsuki-USW/Buzzzzing-Server/settings)에서 변수 APPLICATION_YML을 바꿔야 합니다.

feat: CICD 환경 변수 설정

---

src/main/java/bokjak/bokjakserver/config/security/PrincipalDetails.java
src/main/java/bokjak/bokjakserver/domain/location/controller/LocationController.java
src/main/java/bokjak/bokjakserver/domain/location/service/LocationService.java
src/main/java/bokjak/bokjakserver/domain/user/model/User.java
src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java
src/test/java/bokjak/bokjakserver/domain/location/LocationMockUtils.java
src/test/java/bokjak/bokjakserver/domain/location/LocationServiceTest.java

로케이션 테스트 코드 및 북마크 로직 리팩토링
계획상에 없던 이런 PR은 제목을 어떻게 지어야 할지 모르겠음,,
WBS를 새로 만드는게 좋을까
- x  WBS 업데이트해주세요. (제목에 WBS 번호 달아주세요)

feat: 로케이션 테스트 코드

---

src/main/java/bokjak/bokjakserver/common/dummy/CategoryDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/DummyLocationCategory.java
src/main/java/bokjak/bokjakserver/domain/category/dto/CongestionLevelChoice.java

박스 내용 수정
- 카테고리 종합 삭제
- 정렬 순서 -> 여유순 보통 복쟉순

style: 선택지 박스 업데이트

---

src/main/java/bokjak/bokjakserver/common/constant/ConstraintConstants.java
src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
src/main/java/bokjak/bokjakserver/common/dto/ApiResponse.java
src/main/java/bokjak/bokjakserver/common/dummy/SpotDummy.java
src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
src/main/java/bokjak/bokjakserver/domain/bookmark/repository/SpotBookmarkRepository.java
src/main/java/bokjak/bokjakserver/domain/category/model/LocationCategory.java
src/main/java/bokjak/bokjakserver/domain/category/model/SpotCategory.java
src/main/java/bokjak/bokjakserver/domain/comment/model/Comment.java
src/main/java/bokjak/bokjakserver/domain/congestion/model/Congestion.java
src/main/java/bokjak/bokjakserver/domain/location/controller/LocationController.java
src/main/java/bokjak/bokjakserver/domain/location/dto/LocationDto.java
src/main/java/bokjak/bokjakserver/domain/location/model/Location.java
src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/location/service/LocationService.java
src/main/java/bokjak/bokjakserver/domain/spot/controller/SpotController.java
src/main/java/bokjak/bokjakserver/domain/spot/dto/SpotDto.java
src/main/java/bokjak/bokjakserver/domain/spot/exception/SpotException.java
src/main/java/bokjak/bokjakserver/domain/spot/model/Spot.java
src/main/java/bokjak/bokjakserver/domain/spot/model/SpotImage.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepository.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/spot/service/SpotService.java
src/main/java/bokjak/bokjakserver/domain/user/model/User.java
src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
src/main/java/bokjak/bokjakserver/util/s3/dto/AwsS3Dto.java

스팟 API 구현
- 스팟 리스트 조회
- 내가 쓴 스팟 조회
- 북마크한 스팟 조회
- 스팟 상세 조회
- 스팟 북마크
- 스팟 생성, 수정, 삭제
- 스팟 엔티티 thumbnailImage 부분 삭제
- 로케이션 cursorId 누락 문제 fix
이제 WBS, PR 좀 더 쪼개서 올릴께유 :eyes:

[WBS1-81] 스팟 API 구현

---

src/main/java/bokjak/bokjakserver/common/HelloController.java
src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
src/main/java/bokjak/bokjakserver/config/swagger/SwaggerConfig.java
src/main/java/bokjak/bokjakserver/config/swagger/SwaggerController.java
src/main/java/bokjak/bokjakserver/domain/category/controller/CategoryController.java
src/main/java/bokjak/bokjakserver/domain/location/controller/LocationController.java
src/main/java/bokjak/bokjakserver/domain/spot/controller/SpotController.java
src/main/java/bokjak/bokjakserver/util/s3/controller/AwsS3Controller.java

스웨거 설정 및 명세
[카테고리, 로케이션, 스팟, S3](https://github.com/Akatsuki-USW/Buzzzzing-Server/commit/1ff23532d0438fc7bc43859028861ae6c6b97d6b) 스웨거에 명세
@jinukeu 드디어ㅠㅜ
@woo0doo yml에 스웨거 부분 추가됐읍니다. 노션 수정했어요

[WBS1-260] 스웨거 명세

---

src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
src/main/java/bokjak/bokjakserver/domain/comment/controller/CommentController.java
src/main/java/bokjak/bokjakserver/domain/comment/dto/CommentDto.java
src/main/java/bokjak/bokjakserver/domain/comment/exception/CommentException.java
src/main/java/bokjak/bokjakserver/domain/comment/model/Comment.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
src/main/java/bokjak/bokjakserver/domain/spot/controller/SpotController.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/spot/service/SpotService.java

스팟 댓글 API 구현
구현 : 댓글 생성, 수정, 삭제, 스팟별 댓글 리스트 조회, 내가 댓글 단 스팟 조회

[WBS1-82] 스팟 댓글 API 구현

---

.github/workflows/deploy.yml
.github/workflows/pr-test.yml
.gitignore
Dockerfile
src/main/resources/application-dev.yml
src/main/resources/application.yml

YML 파일 분리
YML 파일을 local, dev로 나눠서 관리. 
민감 정보들은 github 환경 변수에 넣어 관리
:bulb: github 환경 변수 수정하는 경우 : 민감 정보 수정, DB 스키마 변경 (DDL_AUTO를 create으로 변경해줘야 함)

refactor: yml 분리

---

src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
src/main/java/bokjak/bokjakserver/common/dummy/CommentDummy.java
src/main/java/bokjak/bokjakserver/domain/comment/controller/CommentController.java
src/main/java/bokjak/bokjakserver/domain/comment/dto/CommentDto.java
src/main/java/bokjak/bokjakserver/domain/comment/model/Comment.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java

대댓글 조회, 생성, 수정, 삭제
구현 : 조회, 생성
수정 : 기존의 댓글 수정, 삭제
DB 수정 사항 있음! 배포시 시간 좀 걸릴 예정입니다.

[WBS1-287] 스팟 대댓글 API

---

src/main/java/bokjak/bokjakserver/domain/notification/controller/NotificationController.java
src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java
src/main/java/bokjak/bokjakserver/domain/report/controller/ReportController.java
src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java
src/main/java/bokjak/bokjakserver/domain/test/TestController.java
src/main/java/bokjak/bokjakserver/domain/user/controller/AuthController.java
src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java
src/test/java/bokjak/bokjakserver/domain/user/service/UserServiceTest.java

refactor: loginUser 정보 가져오기

---

.gitignore
src/main/resources/application.yml

gitignore 수정
application-dev.yml, application-prod.yml 숨김
PR하기 전에 로컬에서 해당 프로필(dev, prod)로 잘 작동하는지 테스트하면 안정적일듯!

refactor: gitignore dev, prod YML

---

src/main/java/bokjak/bokjakserver/common/dto/PageResponse.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
src/main/java/bokjak/bokjakserver/util/CustomSliceExecutionUtils.java

CustomSliceExecutionUtils : Page 대신에 Slice를 써서 쿼리문 야무지게 고침 
PageResponse에 Slice용 메서드 추가 됐읍니다

fix: 댓글, 대댓글 오래된 순으로 수정 + totalElements 오류 해결

---

src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
src/main/java/bokjak/bokjakserver/domain/notification/dto/NotificationDto.java

댓글 및 대댓글 작성시 알림 가는 기능 개발
댓글 작성 -> spot 작성자에게 알림
대댓글 작성 -> 댓글 작성자에게 알림
댓글 작성자가 대댓글 작성 -> 대댓글에 참여한 모두에게 알림

feat: comment 작성시 알림

---

.gitignore

현재 배포된 쪽은 쟝고 API 데이터를 사용하고 있지만 로컬에서는 사용하기 애매하기 때문에
기존에 쓰던 LocationDummy를 gitignore해서 쓰기로 함
@woo0doo 앱 출시 이후에도 로컬에서 개발하게 되면 Dummy를 쓰는게 편하니깐 이렇게 gitignore해주세유

chore: gitignore 더미 파일

---

src/main/java/bokjak/bokjakserver/domain/user/service/KakaoService.java

refactor: 회원 탈퇴

---

src/main/java/bokjak/bokjakserver/domain/ban/repository/BanRepository.java
src/main/java/bokjak/bokjakserver/domain/ban/repository/BanRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/ban/repository/BanRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/ban/service/BanService.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
src/main/java/bokjak/bokjakserver/domain/notification/repository/NotificationRepository.java
src/main/java/bokjak/bokjakserver/domain/notification/repository/NotificationRepositoryCustom.java
src/main/java/bokjak/bokjakserver/domain/notification/repository/NotificationRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java

notification queryDsl 적용
ban queryDsl 적용

refactor: queryDsl 적용

---

src/main/java/bokjak/bokjakserver/common/dummy/DummyLocationCategory.java
src/main/java/bokjak/bokjakserver/common/dummy/SpotDummy.java
src/main/java/bokjak/bokjakserver/common/dummy/UserDummy.java
src/test/java/bokjak/bokjakserver/domain/location/LocationMockUtils.java

minor: 변경된 AWS 지역 S3 URL 반영

---

src/main/java/bokjak/bokjakserver/domain/comment/dto/CommentDto.java
src/main/java/bokjak/bokjakserver/domain/spot/dto/SpotDto.java
src/main/java/bokjak/bokjakserver/util/web/PreventNullResponseUtils.java

#76 
DTO 변경
nullable값 변경 처리 Util 추가

fix: 탈퇴 유저 필드 null 응답 오류

---

.github/workflows/deploy.yml
Dockerfile

참고 #68 
applicatoin-prod.yml 깃허브 환경 변수로 추가
deploy.yml 수정 : 브랜치 트리거 master로 변경, yml 파일 환경 변수 dev.yml -> prod.yml 변경
DockerFile 수정 : 프로파일을 dev -> prod로 변경
#68

실배포용으로 CICD 파일 변경

---

src/main/java/bokjak/bokjakserver/domain/report/repository/ReportRepository.java
src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java

fix: report 중복 접수

---

README.md
src/main/java/bokjak/bokjakserver/domain/report/repository/ReportRepository.java
src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java

fix: 중복 신고 오류 개선

---

src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java

댓글 수정 작성자 여부 검사 누락
검사 메서드 호출 부분 추가

hotfix: 댓글 수정 작성자 여부 검사 누락

---

src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
src/main/java/bokjak/bokjakserver/config/security/SecurityConfig.java
src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapper.java
src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapperFilter.java

코드 정리
`ReadableRequestBodyWrapperFilter` : Filter 구현체 -> OncePerRequestFilter 상속
SecurityFilter : 메서드 체이닝 순서, 변수명 수정

style: Filter, SerurityConfig 코드 정리

---

src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryImpl.java
src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryImpl.java

페이지네이션 (LIMIT 사용하는) 레포지토리에서 일대다 fetch join 하는 부분들 제거 #93

fix: 페이지네이션 일대다 fetch join 제거

---

src/main/java/bokjak/bokjakserver/util/client/ClientIPAddressUtils.java
src/main/java/bokjak/bokjakserver/web/log/LoggerAspect.java

#99 
해외 IP 요청으로 인한 문제일 수 있어서 IP 로깅 로직 추가
`ClientIPAddressUtils` 추가

feat: IP 로깅 항목 추가
